# -*- mode: ruby -*-
# vi: set ft=ruby :

# provisioning scripts start
$set_tz = <<SCRIPT
ln -s -f /usr/share/zoneinfo/US/Pacific /etc/localtime
SCRIPT

$yum_install = <<SCRIPT
# echo "proxy=http://www-proxy.us.oracle.com:80" >> /etc/yum.conf
# enable Yum repository containing Docker 
yum-config-manager --enable ol7_addons
# yum update to refresh the local yum repository information
yum -y update
# enable X11 Windows desktop
yum -y groupinstall 'X Window System' 'GNOME'
# enable swap (1GB)
dd if=/dev/zero of=/swapfile bs=1M count=1024
mkswap /swapfile
swapon /swapfile
echo "/swapfile       swap       swap       defaults       0 0" >> /etc/fstab
# vncserver
yum -y install tigervnc-server
# emacs
yum -y install emacs
# firefox
yum -y install firefox
# docker
yum -y install docker-engine
# configure Docker service to use http proxy (to download Docker containers)
echo  "[Service] 
Environment=\"HTTP_PROXY=http://www-proxy.us.oracle.com:80\"
Environment=\"HTTPS_PROXY=http://www-proxy.us.oracle.com:80\"" >  /etc/systemd/system/docker.service.d/http-proxy.conf
# activate the new Docker service setting
systemctl daemon-reload
# start the Docker service
systemctl start docker.service
# start the Docker service every time the OS is restarted
systemctl enable docker.service
# Yum cache clean up to free up diskspace (approx. 500 MByte)
yum clean all
SCRIPT

# provisioning scripts end

# vm configuration
nodes_config = (JSON.parse(File.read("nodes.json")))['nodes']

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "oraclelinux-7.1-x86_64"
  config.vm.box_url = "http://cloud.terry.im/vagrant/oraclelinux-7-x86_64.box"

  nodes_config.each do |node|
    node_name = node[0] # name of node
    node_values = node[1] # content of node
    
    config.vm.define node_name do |config|
      # configures all forwarding ports in JSON array
      ports = node_values['ports']
      ports.each do |port|
        config.vm.network :forwarded_port,
        host: port[':host'],
        guest: port[':guest'],
        id: port[':id']
      end
      
      config.vm.hostname = node_values[':node']
#
# a) NAT network, statically assigned addresses
# 
#      config.vm.network :private_network, ip: node_values[':ip']
#
# b) bridge network, DHCP assigned address
#
# Note: 
# 1) bridge: "eth0" specifies the host's network interface which should 
# be used for the bridge (for the VM the network interface will be
# determined dynamically)
# 2) different operating system use different interface names
# 3) Vagrant will prompt the user if the specified interface can not be found
#
      config.vm.network :public_network, type: "dhcp", bridge: "eth0"
#
      
      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", node_values[':memory']]
        vb.customize ["modifyvm", :id, "--name", node_values[':node']]
      end
     config.vm.provision "shell", inline: $set_tz
     config.vm.provision "shell", inline: $yum_install
    end
  end
end 
